CREATE OR REPLACE STREAM "MOST_POPULAR_ITEMS_STREAM" (
    item_id VARCHAR(16),
    views_count INTEGER
);

CREATE OR REPLACE STREAM "MOST_POPULAR_CATEGORIES_STREAM" (
    category VARCHAR(16),
    views_count INTEGER
);

CREATE OR REPLACE STREAM "TOO_POPULAR_ITEMS_ALERTS_STREAM" (
    top_10_views_count INTEGER
);

CREATE OR REPLACE PUMP "MOST_POPULAR_ITEMS_PUMP" AS
    INSERT INTO "MOST_POPULAR_ITEMS_STREAM"
    SELECT STREAM * 
        FROM TABLE (TOP_K_ITEMS_TUMBLING(
            CURSOR(SELECT STREAM * FROM "SOURCE_SQL_STREAM_001"),
            'item_id',
            10,
            60
            )
        );

CREATE OR REPLACE PUMP "MOST_POPULAR_CATEGORIES_PUMP" AS
    INSERT INTO "MOST_POPULAR_CATEGORIES_STREAM"
    SELECT STREAM *
        FROM TABLE (TOP_K_ITEMS_TUMBLING(
            CURSOR(SELECT STREAM * FROM "SOURCE_SQL_STREAM_001" INNER JOIN "ITEMS" as "I" ON "I"."item_id" = "SOURCE_SQL_STREAM_001"."item_id"),
            'item_id',
            10,
            60
            )
        );

CREATE OR REPLACE PUMP "TOO_POPULAR_ITEMS_ALERTS_PUMP" AS
    INSERT INTO "TOO_POPULAR_ITEMS_ALERTS_STREAM"
    SELECT STREAM SUM(views_count) AS top_10_views_count 
        FROM "MOST_POPULAR_ITEMS_STREAM"
        GROUP BY ROWTIME
        HAVING SUM(views_count) > 1000;
